workflows:
  build-android:
    name: Build SmartTrading-D366 APK
    max_build_duration: 60
    environment:
      flutter: 3.22.0
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Clean
        script: |
          flutter clean

      - name: Build APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
